# require docker
sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # download and install google sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # update kubectl
  - gcloud components update kubectl
  # authenticate to google cloud
  - gcloud auth activate-service-account --key-file service-account.json
