# require docker
sudo: required
services:
  - docker

env:
  global:
    # used to set unique docker image version
    - SHA=$(git rev-parse HEAD)
    # make sure travis doesn't run into google cloud sdk prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  # get credentials for gcloud
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # download and install google sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  # update kubectl
  - gcloud components update kubectl
  # authenticate to google cloud and configure cli
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-278720
  - gcloud config set compute/zone us-west1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dmaesj/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dmaesj/react-test npm run test --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
