apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: calcdev-com-tls
spec:
  secretName: calcdev-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: calcdev.com
  dnsNames:
    - calcdev.com
    - www.calcdev.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - calcdev.com
          - www.calcdev.com
