apiVersion: certmanager.k8s.io/v1alpha1
kind: CluserIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "dj@calcdev.com"
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
